version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - app-db:/var/lib/postgresql/data

volumes:
  app-db:
