version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - ./app:/app

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/app:/srv
      - hexlet_devops_project_1_caddy_data:/data
      - caddy_config:/config

volumes:
  hexlet_devops_project_1_caddy_data:
  caddy_config: