version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: 1g0rbm/devops-for-programmers-project-lvl1
    command: ["npm", "test"]
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_DB: $DATABASE_NAME
    volumes:
      - app-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app-db:
