name: push

on:
  push:
    branches:
      - main

env:
  APP_DOCKER_IMAGE_NAME: 1g0rbm/devops-for-programmers-project-lvl1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Create .env file
        run: make create-env

      - name: CI
        run: make ci

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build app
        run: make build

      - name: Push image to dockerhub
        run: make push
